# Generated by Django 2.2.24 on 2021-06-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ombre_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('images', models.ImageField(null=True, upload_to='')),
                ('details', models.TextField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
