# Generated by Django 2.2.24 on 2021-06-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='ombre_detail',
            name='images',
        ),
        migrations.AddField(
            model_name='ombre_detail',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
