# Generated by Django 2.2.24 on 2021-06-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210613_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='name',
            new_name='idi',
        ),
        migrations.RenameField(
            model_name='ombre_detail',
            old_name='num',
            new_name='idi',
        ),
    ]
