# Generated by Django 2.2.24 on 2021-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210613_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ombre_detail',
            name='idi',
            field=models.CharField(max_length=100),
        ),
    ]
