# Generated by Django 2.2.24 on 2021-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20210613_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='idi',
            field=models.CharField(default='nil', max_length=100),
        ),
        migrations.AlterField(
            model_name='ombre_detail',
            name='idi',
            field=models.CharField(default='nill', max_length=100),
        ),
    ]
