# Generated by Django 2.2.24 on 2021-06-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20210613_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ombre_detail',
            name='quantity',
        ),
    ]
