# Generated by Django 2.2.24 on 2021-06-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_ombre_detail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ombre_detail',
            name='details',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
