# Generated by Django 2.2.24 on 2021-06-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20210614_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detail',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
