# Generated by Django 2.2.24 on 2021-06-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0009_auto_20210614_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat', models.CharField(max_length=100)),
                ('idi', models.CharField(default='nill', max_length=100)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('details', models.TextField(max_length=10000, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idi', models.CharField(default='nil', max_length=100)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
